package org.example.backendcrcoach.domain.entities;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name = "clans")
public class Clan {
    @Column(name = "tag", unique = true)
    private String tag;
    @Column(nullable = false)
    private String name;
    @Id
    // badgeId comes from the external Clash Royale API and must not be generated by the DB.
    // We keep it as the entity id but remove the @GeneratedValue so the real badge id
    // provided by the API can be stored here.
    private Long badgeId;
}

