# Puerto de la aplicación
spring.application.name=Backend-CRCoach
server.port=8080
spring.main.banner-mode=off


# ===============================
# DATASOURCE POSTGRESQL (RENDER)
# ===============================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# SQL INIT
# ===============================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR


# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.enable-spring-el-compiler=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.servlet.content-type=text/html


# ===============================
# SPRINGDOC (OpenAPI / Swagger)
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# ===============================
# MAIL (SMTP) - Gmail example
# ===============================
spring.mail.host=${SPRING_HOST}
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8


# ===============================
# CUSTOM PROPERTIES
# ===============================
app.frontend.base-url=${APP_FRONTEND_BASE_URL}
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}
clash.royale.api.key=${CLASH_ROYALE_API_KEY}
clash.royale.api.url=${CLASH_ROYALE_API_URL}

